### ISSUE TITLE
Team Name // Task Division

### ISSUE THREAD

**Issue by JARalph23Z** [JARalph23Z/Calculator#1]
### **Team Name**
So unsa man atong group name? hahaha

### **Task Division**

_Instructions ni Sir_

Let’s assume a group of 4 people. With object oriented-programming, we can easily separate the logic of the calculator from it’s user facing component which is the UI.
• One person will act as the team leader. He will manage the github repository, write some unit tests, and be the one in charged with integrating the calculator logic with the UI. Also, this person must be knowledgeable in merging different git branches together.
• The other one will be in charged of writing the calculator logic. He can also participate in writing the unit tests to assure that the calculator logic is working well.
• The third person will be the one assigned in doing the UI. Python has a lot if available packages that can be used in developing UI components. It is the job of this team member to determine what library will best suit this application. He/she can also write some unit tests to assured UI components are behaving as desired.
• The last member will be in charged with the documentation and should be the one in charged in writing the majority of the unit tests.

**Comment by brxzn** [comment]
burgir hahahahaha

**Comment by JARalph23Z** [comment]
Volunteer na lng mo asa mo gusto ma assign, ako mag code guro ko both UI and Calculator logic.

**Comment by Kkaepsong** [comment]
Goal Diggers HAHAHA

**Comment by JARalph23Z** [comment]
> Goal Diggers HAHAHA

hahahha niceee

**Comment by JARalph23Z** [comment]
**Team Leader: Ralph Palmaira**
He will manage the GitHub repository, write some unit tests, and be the one in charge of integrating the Calculator logic with the UI. He will also be participating in the coding phases of the Calculator and UI. He will also be the one making the boilerplate code for the Calculator.

**Calculator Logic Coder:**
He will be making the bulk of the code of the Calculator. He will also be making some unit tests to test the efficiency of the calculator.

**UI Coder: __ & Ralph Palmaira**
Upon the instructions of the UI Designer, he will be making the code for the GUI. He will also partake in the integration of the Calculator Logic to the UI.

**Test File Coder:**
He will be making sure that all the code in the Calculator Logic and UI are working properly. He will be responsible for making sure that the codes are error-free, and must inform the coders of any errors that will arise with the unit tests they will make.

**UI Designer / Documentation:**
He will be responsible for setting up the desired UI design/theme/layout of the Calculator. He will coordinate with the Team Leader and UI Coder for the efficiency and functionality of the UI. He will also be documenting the different functions of the Calculator, and explaining in detail the modules and libraries used in the code. He will also be responsible for the production of the Video Presentation.

So ari nalang atong final roles if okay lng sa inyoha. Mainly mag code ko sa UI since gainvolve siya og learning a whole library of methods and classes, need ko lng kasama din para makadiscuss kami paano ganito ganyan.

Sa team name, **GOAL DIGGERS** lang ang suggestion? Hahahaha wala nadin akong maisip.

**Comment by brxzn** [comment]
Logic Coder nalang ko ralph, tabanganay lang ta dira hahaha

**Comment by Meriodasu007** [comment]
I will act as the Test File Coder.

**Comment by Meriodasu007** [comment]
> > Goal Diggers HAHAHA
> 
> hahahha niceee

Ben and Friends di ka? HAHAHA

**Comment by Torurae** [comment]
> burgir hahahahaha

Ok nis akoa hahhaha

**Comment by Torurae** [comment]
Burgir Diggers

**Comment by Torurae** [comment]
UI Designer shit ko try

**Comment by JARalph23Z** [comment]
### TEAM BURGIR

**Team Leader: Ralph Palmaira**
He will manage the GitHub repository, write some unit tests, and be the one in charge of integrating the Calculator logic with the UI. He will also be participating in the coding phases of the Calculator and UI. He will also be the one making the boilerplate code for the Calculator.

**Calculator Logic Coder: Brixson Domantay**
He will be making the bulk of the code of the Calculator. He will also be making some unit tests to test the efficiency of the calculator.

**UI Coder: Ralph Palmaira**
Upon the instructions of the UI Designer, he will be making the code for the GUI. He will also partake in the integration of the Calculator Logic to the UI.

**Test File Coder: Hans Tulayan**
He will be making sure that all the code in the Calculator Logic and UI are working properly. He will be responsible for making sure that the codes are error-free, and must inform the coders of any errors that will arise with the unit tests they will make.

**UI Designer / Documentation: Ray Dalipe and Saile Galilea**
He will be responsible for setting up the desired UI design/theme/layout of the Calculator. He will coordinate with the Team Leader and UI Coder for the efficiency and functionality of the UI. He will also be documenting the different functions of the Calculator, and explaining in detail the modules and libraries used in the code. He will also be responsible for the production of the Video Presentation.

So ani na ang Team Name and Task Division, react kayo "Like" if wala na problema, otherwise comment lng para ma discuss.

**Comment by brxzn** [comment]
kahadlok logic coder wahahah carry me ralph

**Comment by JARalph23Z** [comment]
Lagii HAHAHA ikaw lng sa akong gibutang

**Comment by JARalph23Z** [comment]
So murag wala na man issues noh, I close ko na ito and I submit ko na ang form. Go **TEAM BURGIR**
