### ISSUE TITLE
Video Presentation

### ISSUE THREAD

**Issue by JARalph23Z** [JARalph23Z/Calculator#11]
Guys discuss ta diri kung unsa atong himuon sa video.

So mura siyag "baligya baligya" kumbaga, i-present nato ang features sa atong calculators, iexplain natin paano natin na achieve (anong libraries and imports gamit), tsaka mga challenges na naencounter natin.

Point person dito mga assigned sa Documentation, @Torurae and @Kkaepsong. Thank you!

**Comment by Torurae** [comment]
Guys nag buhat kog skit para sa atong video, murag tung aggressive gud na naga balgya sa cartoon network tung ga boxing na fingers

**Comment by Torurae** [comment]
kung medjo ngi or kulang kay dungagan nato.

**Comment by brxzn** [comment]
https://drive.google.com/drive/folders/1OyB4JLE4hslTJQYmSVOpSSSg1oIPM7MX?usp=sharing

Calculator Demo. Gi google drive ko nalang kay nag exceed 20mb ang file size.

PS paki check kung okay

**Comment by brxzn** [comment]
If low quality diay sya, pwede rapod nako i gmail sa inyo. Wala ko kabalo ngano 360p lang sya pag upload sa drive pero 200 mb - 5min clip lol
