### ISSUE TITLE
Video Presentation Script

### ISSUE THREAD

**Issue by Torurae** [JARalph23Z/Calculator#13]
Diri guys ang iskrip nato ug ang flow kumbaga, kung gusto nato naay baguhon or dungagan comment down below for jowa nalang. Kini ang script tentative nato: 
[CCC Video Presentation.docx](https://github.com/JARalph23Z/Calculator/files/6763415/CCC.Video.Presentation.docx)

**Comment by Torurae** [comment]
Kini ang sa screen record
[CCC Video ShareScreen.docx](https://github.com/JARalph23Z/Calculator/files/6767555/CCC.Video.ShareScreen.docx)

**Comment by Torurae** [comment]
Finaled
[CCC Video Presentation.docx](https://github.com/JARalph23Z/Calculator/files/6770499/CCC.Video.Presentation.docx)

**Comment by JARalph23Z** [comment]
[CCC Video Presentation.docx](https://github.com/JARalph23Z/Calculator/files/6770738/CCC.Video.Presentation.docx)
May gi edit lang ako na mga lines.
[CCC Video ShareScreen.docx](https://github.com/JARalph23Z/Calculator/files/6770791/CCC.Video.ShareScreen.docx)
Changed some problems.
