### ISSUE TITLE
UI and Features

### ISSUE THREAD

**Issue by JARalph23Z** [JARalph23Z/Calculator#2]
Hello guys, so nagtry-try lang ko og himo og UI, tingnan niyo sa main branch. Download niyo yung `Basic Scientific Calculator UI` and I run niyo para makita niyo.

As you can see if you successfully ran it, merong menu sa taas, para makapili ang user kung anong klase na calculator ang gamitin nila. Nakadefault ang window sa Scientific Calculator, tas pag I click nila ang Simple Calculator, mag change lng siya to yang normal na calculator (numbers and basic operators lng). 

Then I wanted to go extra nag lagay muna ako ng Units Converter (metric and English), money converter (though currency converter guro mas chuy) tsaka Automatic Solver.

Para sa Automatic Solver, simple lng din muna na features ginaisip ko hahah di rin yung pang Symbolab talaga, yang kunware Area & Circumference Solver, mag ask lng siya sa user ng Radius and automatic na ibigay ng ating calculator ang answer. 

So bale sa Units & Currency Converter and Automatic Solver natin, di niya i replace ang main window. Mag create siya ng bagong window (or baka mag add siya ng window katabi sa main calculator natin? let's discuss hahaha)

So what we need to discuss in this issue kay ang FINAL SET OF FEATURES natin, and also some GENERAL IDEAS for the UI like COLOR THEMES, ICONS, DESIGN & LAYOUT, etc. just to start.

PLEASE MAG-REPLY DIN KAYO PARA MAKASTART SAD TA DAYUN. Ugma na ang first na evaluation hahaha dapat matapos natin ang dalawang issue na nandito ngayon.

**Comment by brxzn** [comment]
what if layout kagaya nung sci-cal sa casio??? pero baka mahirap

**Comment by JARalph23Z** [comment]
Kato pud ginaisip nako hahaha pilian lng nato og functions kay di man guro nato makaya makahimo og sigma or derivatives or katung mga table table og graph hahaha.

**Comment by JARalph23Z** [comment]
```
Numeric keypad (0-9) with decimal point
Can perform addition (+) , subtraction (-), multiplication (x), and division (%)
Can perform trigonometric operations (sine, cosine, tangent, inverses, etc.)
Can perform logarithmic and exponential operations
Can perform other algebraic operations (square root, cube root, scientific notations, factorials, etc.)
Capable of chaining multiple operations together (with or without parentheses) and execute them in the correct order
Other necessary functions: delete, clear all, inverse and reciprocal, etc.
```

Kani ra so far akong naisip, i implement nato tung shift? or okay na yung nasa screen na lahat ng functions daan. feel ko mas madali

**Comment by Kkaepsong** [comment]
Tung nasa screen na lahat ng functions daan para di mag lisod

**Comment by Kkaepsong** [comment]
Tung nasa screen na lahat ng functions daan para di mag lisod

**Comment by JARalph23Z** [comment]
```
Numeric keypad (0-9) with decimal point
Can perform addition (+) , subtraction (-), multiplication (x), and division (%)
Can perform trigonometric operations (sine, cosine, tangent, inverses, etc.)
Can perform logarithmic and exponential operations
Can perform other algebraic operations (square root, cube root, scientific notations, factorials, etc.)
Capable of chaining multiple operations together (with or without parentheses) and execute them in the correct order
Other necessary functions: delete, clear all, inverse and reciprocal, etc.
```

So far mao man ni siya ang features jud sa calculator, karon ga isip isip na pud ko sa features sa UI.

I assume nakita niyo na man yung video na gisend ko sa GC hahaha.
UI Designers palihog lng pud ko isip og design sa basic calculator tsaka scientific calculator. Tan-awa lng tung video as basis pero di jud siya ato jud, mag pina Casio Sci-cal man kaya ta haha. Palihog lng pud ko incorporate og Date/Time kung asa siya dapit ibutang kay iimplement nako sa sa UI. salamat!!

No rush, just try to reply lng by the end of the week.

**Comment by Torurae** [comment]
Flapper jappers mangita rakos googs ug nawng sa atong calc?

**Comment by JARalph23Z** [comment]
> Flapper jappers mangita rakos googs ug nawng sa atong calc?

okay na man ray, nag send si saile, pero kung naa kay suggestion sa theme/design discuss lang mo hahaha tas pagingon lang matsalaa

**Comment by Torurae** [comment]
Meron akong modified ver na burger faced na calc
